### ISSUE TITLE
Windows installation command can be shorten

### ISSUE THREAD

**Issue by YouJiacheng** [mamba-org/micromamba-releases#19]
`Invoke-Expression ((Invoke-WebRequest -Uri https://micro.mamba.pm/install.ps1).Content)` can be simplified to
`irm https://micro.mamba.pm/install.ps1 | iex`, where `irm -> Invoke-RestMethod` and `iex -> Invoke-Expression` are built-in aliases.

**Comment by jjerphan** [comment]
See https://github.com/mamba-org/micromamba-releases/pull/20#issuecomment-2514339666.
