### ISSUE TITLE
install.ps1 seems not to initialize PowerShell according to the prefix entered by the user

### ISSUE THREAD

**Issue by pk5ls20** [mamba-org/micromamba-releases#40]
In the current version of install.ps1 (https://github.com/mamba-org/micromamba-releases/commit/946ea168f610f3d8f7cdb25c12561ba286a59d75), although the installation script asks the user if they want to initialize using a custom prefix, this variable is not used during the actual initialization process. This can lead to results that are inconsistent with the user's expectations after installation.

See https://github.com/mamba-org/micromamba-releases/blame/946ea168f610f3d8f7cdb25c12561ba286a59d75/install.ps1#L41 and below.

<img width="794" alt="image" src="https://github.com/mamba-org/micromamba-releases/assets/114645197/8594ba01-8552-4327-805d-c8ce728540b7">

**Comment by colour-y** [comment]
tql
