### ISSUE TITLE
Don't mark micromamba rc's as latest release in github

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/micromamba-releases#49]
setup-micromamba uses the `latest` release by default which results in the rc being rolled out to too many users.

![image](https://github.com/user-attachments/assets/46061cfc-d460-4643-8b12-039de1123a3f)

**Comment by pavelzw** [comment]
@JohanMabille @Klaim @AntoinePrv

**Comment by JohanMabille** [comment]
Indeed, this was made by accident and has been fixed in the latest commit.

**Comment by pavelzw** [comment]
you still need to mark it as not `latest` in https://github.com/mamba-org/micromamba-releases/blob/b005df81f0367804ce2e1255d7e2cb08c891cc3d/.github/workflows/release.yml#L30

@wolfv just made it a pre-release manually

![image](https://github.com/user-attachments/assets/afcd390b-3731-477e-a327-0bb92d7c55d3)

Once you trigger this workflow a second time for rc1, it will be `latest` again

**Comment by JohanMabille** [comment]
Shouldn't [the latest commit](https://github.com/mamba-org/micromamba-releases/commit/b005df81f0367804ce2e1255d7e2cb08c891cc3d) prevent this issue?

**Comment by pavelzw** [comment]
not that i can see 🤔 you need to specify `prerelease: true` for these kinds of releases

https://github.com/softprops/action-gh-release/blob/288696be3916479e99fa944c72825e9b3e192be4/action.yml#L21

**Comment by JohanMabille** [comment]
It looks like this is filtered in the [fetch_release.py script](https://github.com/mamba-org/micromamba-releases/blob/main/fetch_release.py#L63-L66). The latest commits guarantees that the rlease workflow will never invoke the script with an argument. I agree we could make this more explicit with the prerelease tags.

**Comment by Hind-M** [comment]
All dev and prereleases will be skipped when the workflow is triggered automatically unless it's done manually (cf. #46 and #47), but in that case, and if the version is a prerelease, it won't indeed be marked as a prerelease.
#50 should fix it.
