### ISSUE TITLE
Environment creation fails with relative path

### ISSUE THREAD

**Issue by amgcc** [mamba-org/micromamba-releases#57]
Running micromamba create and pointing the prefix to a relative path fails in error when the input file contains a `pip` section.  This behavior occurs on both windows and linux.

`micromamba env create --yes -f deps.yaml -p folder/subfolder`

```
critical libmamba Cannot activate, prefix does not exist at: 'folder/subfolder'
/tmp/mambafKZrZk11KQo: line 5: folder/subfolder/bin/python: No such file or directory
critical libmamba pip failed to install packages
```

**Comment by Hind-M** [comment]
This issue should be opened in the `mamba` repo: cf. https://github.com/mamba-org/mamba/issues/3631
