### ISSUE TITLE
[BUG] micromamba 2.0.3 "could not load prefix data"

### ISSUE THREAD

**Issue by jnooree** [mamba-org/micromamba-releases#62]
In a github action using mamba-org/setup-micromamba@v2.0.1, `micromamba list` step fails on a github-hosted runner when run with micromamba `2.0.3-0`, but success with `2.0.2-2`.

The error message was `could not load prefix data`, as in the title.

**Comment by jjerphan** [comment]
Hello,

Thank you for the report.

Can you open an issue on the issue tracker of `mamba` upstream?

Thank you.
