### ISSUE TITLE
micromamba 1.5.0 gives error package is not available for the specified platform

### ISSUE THREAD

**Issue by msmitherdc** [mamba-org/micromamba-releases#9]
critical libmamba The package "/tmp/linux-64/xxxx.tar.bz3" is not available for the specified platform

Failing back to 1.4.9 it all works, but some change at 1.5.0 caused this.

I install a package from conda-forge and then install locally built plugins for that package using micromamba. But cannot install the local package since the latest release

**Comment by jonashaag** [comment]
Please open a bug report at https://github.com/mamba-org/mamba with more details.

**Comment by jonashaag** [comment]
@wolfv @AntoinePrv can someone grant me "close issue" permissions in this repo?

**Comment by AntoinePrv** [comment]
I do not have such rights
